stages:
  - build

variables:
  IMAGE_NAME: "$HARBOR_REGISTRY/ai-sqlbot/sqlbot-backend"
  IMAGE_TAG: "test-v0.0.1"

build-test:
  stage: build
  tags:
    - sqlbot
  image: docker:27

  script:
    - echo "$HARBOR_PASSWORD" | docker login "$HARBOR_REGISTRY" -u "$HARBOR_USERNAME" --password-stdin

    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .

    - docker push "$IMAGE_NAME:$IMAGE_TAG"